#!/usr/bin/env bun
/**
 * Generate the RSA keypair used to sign Pro license JWTs.
 *
 * Output:
 *   src/core/license/public-key.ts   — PEM constant, committed to the public repo
 *   .agents/private/license-priv.pem — NEVER commit; copy this to the issuer
 *
 * Runs in Bun via `bun scripts/license/generate-keypair.ts`. Idempotent — re-running
 * will refuse to overwrite an existing private key unless `--force` is passed,
 * because rotating the key invalidates every license in the wild.
 *
 * Rotation procedure (when you do need to rotate):
 *   1. Run with --force, get new keys.
 *   2. Bump KERNEL public-key.ts.
 *   3. Issuer flips to the new private key.
 *   4. Re-issue licenses for every active customer (one-time mass email).
 *   5. Old JWTs stop validating on the next kernel restart.
 *
 * Don't rotate without a real reason. The public key lives in every binary
 * shipped to users.
 */

import { mkdir, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { generateKeyPairSync } from "node:crypto";

const ROOT = resolve(import.meta.dir, "..", "..");
const PUBLIC_OUT = resolve(ROOT, "src/core/license/public-key.ts");
const PRIVATE_OUT = resolve(ROOT, ".agents/private/license-priv.pem");

const force = process.argv.includes("--force");

if (existsSync(PRIVATE_OUT) && !force) {
  console.error(`✖  ${PRIVATE_OUT} already exists. Refusing to overwrite without --force.`);
  console.error(`   Rotating the key invalidates every license in the wild — read the script header first.`);
  process.exit(1);
}

console.log("Generating RSA-2048 keypair…");
const { publicKey, privateKey } = generateKeyPairSync("rsa", {
  modulusLength: 2048,
  publicKeyEncoding:  { type: "spki",  format: "pem" },
  privateKeyEncoding: { type: "pkcs8", format: "pem" },
});

await mkdir(dirname(PRIVATE_OUT), { recursive: true });
await writeFile(PRIVATE_OUT, privateKey, { mode: 0o600 });
console.log(`✓ Wrote private key  → ${PRIVATE_OUT}  (chmod 600)`);

// Embed as a TypeScript constant so the kernel doesn't have to ship a separate
// .pem file. The template-literal preserves newlines without escape-fest.
const publicKeyTs = `/**
 * Public key for verifying Pro license JWTs (RS256).
 *
 * AUTO-GENERATED by scripts/license/generate-keypair.ts — do not edit by hand.
 * Rotating it requires re-issuing every license; read the generator script
 * header before considering it.
 */

export const LICENSE_PUBLIC_KEY = \`${publicKey.trim()}
\`;
`;

await writeFile(PUBLIC_OUT, publicKeyTs, "utf-8");
console.log(`✓ Wrote public key   → ${PUBLIC_OUT}`);

// Quick sanity check — verify we can round-trip a token with this pair using
// Web Crypto (the same path the kernel uses). Catches encoding mistakes early.
async function sanityCheck() {
  const enc = new TextEncoder();
  const header = btoa(JSON.stringify({ alg: "RS256", typ: "JWT" })).replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
  const body   = btoa(JSON.stringify({ iss: "test", sub: "test", iat: 1, exp: 2 })).replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
  const data   = enc.encode(`${header}.${body}`);

  const priv = await crypto.subtle.importKey(
    "pkcs8",
    pemToArrayBuffer(privateKey, "PRIVATE KEY"),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false, ["sign"],
  );
  const sigBuf = await crypto.subtle.sign("RSASSA-PKCS1-v1_5", priv, data);
  const sig = btoa(String.fromCharCode(...new Uint8Array(sigBuf))).replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");

  const pub = await crypto.subtle.importKey(
    "spki",
    pemToArrayBuffer(publicKey, "PUBLIC KEY"),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false, ["verify"],
  );
  const ok = await crypto.subtle.verify(
    "RSASSA-PKCS1-v1_5",
    pub,
    Uint8Array.from(atob(sig.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(sig.length / 4) * 4, "=")), c => c.charCodeAt(0)),
    data,
  );
  if (!ok) throw new Error("Round-trip verify failed — keys don't match.");
  console.log("✓ Sanity check passed (sign + verify round-trip).");
}

function pemToArrayBuffer(pem: string, label: string): ArrayBuffer {
  const base64 = pem
    .replace(`-----BEGIN ${label}-----`, "")
    .replace(`-----END ${label}-----`, "")
    .replace(/\s+/g, "");
  const bin = atob(base64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  return buf.buffer;
}

await sanityCheck();

console.log("");
console.log("⚠ Add `.agents/private/` to your gitignore if it isn't already.");
console.log("⚠ Copy .agents/private/license-priv.pem to the issuer Worker (Cloudflare secret).");
