/**
 * Onboarding Wizard
 * Interactive setup for Kernl
 */

import { createInterface } from "readline";
import { randomBytes } from "crypto";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { join, dirname } from "path";

interface WizardAnswers {
  sqlitePath: string;
  dashboardEnabled: boolean;
  dashboardPort: number;
  telegramEnabled: boolean;
  telegramToken: string;
  telegramUsers: string[];
  whatsappEnabled: boolean;
  slackEnabled: boolean;
  discordEnabled: boolean;
  voiceEnabled: boolean;
  neo4jEnabled: boolean;
}

/**
 * Run the onboarding wizard
 */
export async function runWizard(): Promise<void> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const ask = (question: string): Promise<string> => {
    return new Promise((resolve) => {
      rl.question(question, resolve);
    });
  };

  const askBool = async (question: string, defaultValue = false): Promise<boolean> => {
    const defaultStr = defaultValue ? "Y/n" : "y/N";
    const answer = await ask(`${question} [${defaultStr}]: `);
    if (!answer) return defaultValue;
    return answer.toLowerCase().startsWith("y");
  };

  console.log("\n===================================");
  console.log("   Kernl Onboarding Wizard");
  console.log("===================================\n");

  console.log("This wizard will help you set up Kernl.\n");

  const answers: WizardAnswers = {
    sqlitePath: "",
    dashboardEnabled: true,
    dashboardPort: 3086,
    telegramEnabled: false,
    telegramToken: "",
    telegramUsers: [],
    whatsappEnabled: false,
    slackEnabled: false,
    discordEnabled: false,
    voiceEnabled: false,
    neo4jEnabled: false,
  };

  // Database
  console.log("--- Database ---");
  const defaultDbPath = "./data/kernel.db";
  const dbPath = await ask(`SQLite database path [${defaultDbPath}]: `);
  answers.sqlitePath = dbPath || defaultDbPath;

  // Dashboard
  console.log("\n--- Dashboard ---");
  answers.dashboardEnabled = await askBool("Enable web dashboard?", true);
  if (answers.dashboardEnabled) {
    const portStr = await ask("Dashboard port [3086]: ");
    answers.dashboardPort = parseInt(portStr, 10) || 3086;
  }

  // Telegram
  console.log("\n--- Telegram ---");
  answers.telegramEnabled = await askBool("Enable Telegram bot?", false);
  if (answers.telegramEnabled) {
    answers.telegramToken = await ask("Telegram bot token: ");
    const usersStr = await ask("Allowed user IDs (comma-separated): ");
    answers.telegramUsers = usersStr.split(",").map((s) => s.trim()).filter(Boolean);
  }

  // Other channels
  console.log("\n--- Other Channels ---");
  answers.whatsappEnabled = await askBool("Enable WhatsApp?", false);
  answers.slackEnabled = await askBool("Enable Slack?", false);
  answers.discordEnabled = await askBool("Enable Discord?", false);

  // Voice
  console.log("\n--- Voice ---");
  answers.voiceEnabled = await askBool("Enable voice (requires OpenAI API key)?", false);

  // Neo4j
  console.log("\n--- Graph Database ---");
  answers.neo4jEnabled = await askBool("Enable Neo4j (docker compose up -d)?", false);

  rl.close();

  // Generate .env file
  console.log("\n--- Generating Configuration ---\n");
  const envContent = generateEnvFile(answers);
  
  const envPath = ".env";
  const existingEnv = existsSync(envPath);
  
  if (existingEnv) {
    console.log("Existing .env found. New configuration:");
    console.log("----------------------------------------");
    console.log(envContent);
    console.log("----------------------------------------");
    console.log("\nTo apply, replace your .env with the above content.");
  } else {
    writeFileSync(envPath, envContent);
    console.log(`Created ${envPath}`);
  }

  // Create data directory
  const dataDir = dirname(answers.sqlitePath);
  if (!existsSync(dataDir)) {
    mkdirSync(dataDir, { recursive: true });
    console.log(`Created ${dataDir}`);
  }

  // Next steps
  console.log("\n--- Next Steps ---\n");
  console.log("1. Review your .env file");
  
  if (answers.telegramEnabled && !answers.telegramToken) {
    console.log("2. Get a Telegram bot token from @BotFather");
  }
  
  if (answers.neo4jEnabled) {
    console.log("3. Start Neo4j: docker compose up -d");
  }
  
  console.log(`${answers.neo4jEnabled ? "4" : "3"}. Start the server: bun run dev`);
  
  if (answers.dashboardEnabled) {
    console.log(`${answers.neo4jEnabled ? "5" : "4"}. Open dashboard: http://localhost:${answers.dashboardPort}`);
  }

  console.log("\nSetup complete!\n");
}

/**
 * Generate .env file content
 */
function generateEnvFile(answers: WizardAnswers): string {
  const lines: string[] = [];

  lines.push("# Kernl Configuration");
  lines.push("# Generated by wizard");
  lines.push("");

  // Database
  lines.push("# Database");
  lines.push(`SQLITE_PATH=${answers.sqlitePath}`);
  lines.push("");

  // Security — generated so the kernel boots authenticated out of the box.
  // The kernel refuses to start with an empty KERNEL_AUTH_TOKEN (open API),
  // and KERNEL_ENCRYPTION_KEY is required to store channel secrets at rest.
  lines.push("# Security (auto-generated — keep secret, do not commit)");
  lines.push(`KERNEL_AUTH_TOKEN=${randomBytes(32).toString("hex")}`);
  lines.push(`KERNEL_ENCRYPTION_KEY=${randomBytes(32).toString("hex")}`);
  lines.push("");

  // Neo4j
  lines.push("# Neo4j (optional)");
  if (answers.neo4jEnabled) {
    const neo4jPass = randomBytes(16).toString("hex");
    lines.push("NEO4J_URI=bolt://localhost:17687");
    lines.push("NEO4J_USER=neo4j");
    lines.push(`NEO4J_PASSWORD=${neo4jPass}`);
  } else {
    lines.push("# NEO4J_URI=bolt://localhost:17687");
    lines.push("# NEO4J_USER=neo4j");
    lines.push("# NEO4J_PASSWORD=");
  }
  lines.push("");

  // Dashboard
  lines.push("# Dashboard");
  lines.push(`DASHBOARD_ENABLED=${answers.dashboardEnabled}`);
  lines.push(`DASHBOARD_PORT=${answers.dashboardPort}`);
  lines.push("");

  // Telegram
  lines.push("# Telegram");
  lines.push(`TELEGRAM_ENABLED=${answers.telegramEnabled}`);
  if (answers.telegramEnabled) {
    lines.push(`TELEGRAM_BOT_TOKEN=${answers.telegramToken}`);
    lines.push(`TELEGRAM_ALLOWED_USERS=${answers.telegramUsers.join(",")}`);
  } else {
    lines.push("# TELEGRAM_BOT_TOKEN=");
    lines.push("# TELEGRAM_ALLOWED_USERS=");
  }
  lines.push("");

  // WhatsApp
  lines.push("# WhatsApp");
  lines.push(`WHATSAPP_ENABLED=${answers.whatsappEnabled}`);
  if (answers.whatsappEnabled) {
    lines.push("WHATSAPP_AUTH_PATH=./data/whatsapp-auth");
    lines.push("# WHATSAPP_ALLOWED_NUMBERS=");
  }
  lines.push("");

  // Slack
  lines.push("# Slack");
  lines.push(`SLACK_ENABLED=${answers.slackEnabled}`);
  if (answers.slackEnabled) {
    lines.push("# SLACK_BOT_TOKEN=");
    lines.push("# SLACK_APP_TOKEN=");
  }
  lines.push("");

  // Discord
  lines.push("# Discord");
  lines.push(`DISCORD_ENABLED=${answers.discordEnabled}`);
  if (answers.discordEnabled) {
    lines.push("# DISCORD_BOT_TOKEN=");
  }
  lines.push("");

  // Voice
  lines.push("# Voice");
  lines.push(`VOICE_ENABLED=${answers.voiceEnabled}`);
  if (answers.voiceEnabled) {
    lines.push("# OPENAI_API_KEY=");
    lines.push("# ELEVENLABS_API_KEY=");
  }
  lines.push("");

  // Logging
  lines.push("# Logging");
  lines.push("LOG_LEVEL=info");
  lines.push("");

  return lines.join("\n");
}

/**
 * CLI entry point
 */
export async function main(): Promise<void> {
  try {
    await runWizard();
  } catch (err) {
    console.error("Wizard error:", err);
    process.exit(1);
  }
}

// Run if called directly
main().catch(console.error);
