/**
 * Policy file loader for `data/workspaces/{id}/.evolve/policy.json`.
 *
 * The policy is stored as JSON (not YAML) to avoid pulling in a parser dep —
 * the kernel runs on stock Node and uses zero YAML elsewhere in tree.
 */

import { readFile, writeFile, mkdir, chmod } from "node:fs/promises";
import { resolve } from "node:path";
import { checkProtected } from "../../../../../../src/core/protected-files.js";
import type { WorkspacePolicy } from "./types.js";

export const POLICY_RELPATH = ".evolve/policy.json";
export const OBJECTIVES_RELPATH = "EVOLUTION.md";
export const CHECKS_RELPATH = ".evolve/checks/run-all.sh";
/** Windows runs the check through cmd.exe, which cannot execute a .sh file. */
export const CHECKS_RELPATH_WIN = ".evolve/checks/run-all.cmd";

/** Default policy seeded by `init`. Conservative: nothing mutable until the
 *  user decides what's safe to touch. */
export const DEFAULT_POLICY: WorkspacePolicy = {
  version: 1,
  mutable_globs: [],
  protected_globs: [],
  evaluation: {
    command: "./.evolve/checks/run-all.sh",
    timeout_s: 300,
  },
  budget: {
    commit_margin: 1.5,
    max_iterations_per_cycle: 3,
  },
};

/** The default policy for the platform the kernel runs on: on Windows the
 *  check is a .cmd script, run by cmd.exe from the workspace root. */
export function defaultPolicyFor(platform: NodeJS.Platform = process.platform): WorkspacePolicy {
  if (platform !== "win32") return DEFAULT_POLICY;
  return {
    ...DEFAULT_POLICY,
    evaluation: { ...DEFAULT_POLICY.evaluation, command: ".evolve\\checks\\run-all.cmd" },
  };
}

export const DEFAULT_OBJECTIVES_MD = `# EVOLUTION

> This file is read by the kernel's workspace evolver before every cycle.
> Keep it focused: mission, invariants, and what "better" actually means.

## Mission

(Describe what this workspace is for. One paragraph.)

## Invariants — must always hold

- (e.g. \`bun test\` exits 0)
- (e.g. The HTTP API stays backwards compatible)
- (e.g. No new dependencies without justification in the run notes)

## Success criteria — what improvement looks like

- (e.g. Lower p95 latency on the /search endpoint)
- (e.g. Fewer TODO comments in src/)

## Out of scope

- (e.g. UI rewrites)
- (e.g. Switching language runtime)
`;

export const DEFAULT_CHECKS_SH = `#!/bin/sh
# Auto-generated by Kernl workspace-evolver init.
# Edit me — this script's exit code IS the success signal for the optimizer.
# Exit 0 = the workspace is in a good state. Anything else = reject.

set -e

# Examples — uncomment what makes sense for this project:
# bun test
# npm test --silent
# python -m pytest -q
# cargo test --quiet

echo "no checks configured — edit ${0}" >&2
exit 1
`;

/** The Windows counterpart of DEFAULT_CHECKS_SH, run by cmd.exe. */
export const DEFAULT_CHECKS_CMD = `@echo off
rem Auto-generated by Kernl workspace-evolver init.
rem Edit me - this script's exit code IS the success signal for the optimizer.
rem Exit 0 = the workspace is in a good state. Anything else = reject.

rem Examples - uncomment what makes sense for this project:
rem call bun test || exit /b 1
rem call npm test --silent || exit /b 1
rem python -m pytest -q || exit /b 1

echo no checks configured - edit %~f0 1>&2
exit /b 1
`;

export interface LoadedPolicy {
  policy: WorkspacePolicy;
  source: "file" | "default";
}

/** Read .evolve/policy.json. Returns null when missing or malformed. */
export async function loadPolicy(workspaceDir: string): Promise<WorkspacePolicy | null> {
  const path = resolve(workspaceDir, POLICY_RELPATH);
  let raw: string;
  try {
    raw = await readFile(path, "utf8");
  } catch {
    return null;
  }
  try {
    const parsed = JSON.parse(raw);
    return validatePolicy(parsed);
  } catch {
    return null;
  }
}

/** Strict shape check. Returns null on any structural mismatch. */
export function validatePolicy(input: unknown): WorkspacePolicy | null {
  if (!input || typeof input !== "object") return null;
  const o = input as Record<string, unknown>;
  if (o.version !== 1) return null;
  if (!Array.isArray(o.mutable_globs) || !o.mutable_globs.every((g) => typeof g === "string")) return null;
  if (!Array.isArray(o.protected_globs) || !o.protected_globs.every((g) => typeof g === "string")) return null;
  const ev = o.evaluation as Record<string, unknown> | undefined;
  if (!ev || typeof ev !== "object") return null;
  if (typeof ev.command !== "string" || ev.command.trim() === "") return null;
  if (typeof ev.timeout_s !== "number" || ev.timeout_s <= 0 || ev.timeout_s > 3600) return null;
  if (ev.cwd != null && typeof ev.cwd !== "string") return null;

  const out: WorkspacePolicy = {
    version: 1,
    mutable_globs: o.mutable_globs as string[],
    protected_globs: o.protected_globs as string[],
    evaluation: {
      command: ev.command,
      timeout_s: ev.timeout_s,
      cwd: typeof ev.cwd === "string" ? ev.cwd : undefined,
    },
  };
  if (o.budget && typeof o.budget === "object") {
    const b = o.budget as Record<string, unknown>;
    out.budget = {};
    if (typeof b.commit_margin === "number") out.budget.commit_margin = b.commit_margin;
    if (typeof b.max_iterations_per_cycle === "number") out.budget.max_iterations_per_cycle = b.max_iterations_per_cycle;
  }
  if (o.constraints && typeof o.constraints === "object") {
    const c = o.constraints as Record<string, unknown>;
    out.constraints = {};
    if (typeof c.max_files_changed_per_run === "number") out.constraints.max_files_changed_per_run = c.max_files_changed_per_run;
    if (Array.isArray(c.forbidden_packages) && c.forbidden_packages.every((p) => typeof p === "string")) {
      out.constraints.forbidden_packages = c.forbidden_packages as string[];
    }
  }
  return out;
}

export interface InitResult {
  policyPath: string;
  objectivesPath: string;
  checksPath: string;
  policyCreated: boolean;
  objectivesCreated: boolean;
  checksCreated: boolean;
}

/**
 * Scaffold the three files in a workspace if they don't exist.
 * Idempotent: re-running never overwrites existing content. Returns flags
 * so the caller can tell what was actually written.
 */
export async function initEvolutionFiles(
  workspaceDir: string,
  platform: NodeJS.Platform = process.platform,
): Promise<InitResult> {
  // On Windows the evaluator runs the check through cmd.exe, which cannot
  // execute run-all.sh — seed a .cmd and point the policy at it instead.
  const windows = platform === "win32";
  const policyPath = resolve(workspaceDir, POLICY_RELPATH);
  const objectivesPath = resolve(workspaceDir, OBJECTIVES_RELPATH);
  const checksPath = resolve(workspaceDir, windows ? CHECKS_RELPATH_WIN : CHECKS_RELPATH);

  await mkdir(resolve(workspaceDir, ".evolve/checks"), { recursive: true });

  const policyCreated = await writeIfMissing(policyPath, JSON.stringify(defaultPolicyFor(platform), null, 2) + "\n");
  const objectivesCreated = await writeIfMissing(objectivesPath, DEFAULT_OBJECTIVES_MD);
  const checksCreated = windows
    ? await writeIfMissing(checksPath, DEFAULT_CHECKS_CMD)
    : await writeIfMissing(checksPath, DEFAULT_CHECKS_SH, 0o755);

  return { policyPath, objectivesPath, checksPath, policyCreated, objectivesCreated, checksCreated };
}

async function writeIfMissing(path: string, content: string, mode?: number): Promise<boolean> {
  try {
    await readFile(path, "utf8");
    return false;
  } catch {
    await writeFile(path, content, { encoding: "utf8" });
    if (mode !== undefined) await chmod(path, mode);
    return true;
  }
}

/**
 * Decide whether a path inside the workspace is allowed to be mutated. A path
 * is allowed iff it is NOT globally protected, NOT in the project's
 * protected_globs, and (if mutable_globs is non-empty) matches mutable_globs.
 *
 * Globs supported: very small subset — `**` for any-depth, `*` for one
 * segment. No bracket expansion, no negation. We intentionally keep this
 * minimal to avoid a glob lib; the policy file documents what's supported.
 */
export function isPathMutable(relPath: string, policy: WorkspacePolicy): { allowed: boolean; reason?: string } {
  if (checkProtected(relPath)) {
    return { allowed: false, reason: "global protected-files rule" };
  }
  for (const g of policy.protected_globs) {
    if (matchSimpleGlob(relPath, g)) {
      return { allowed: false, reason: `policy.protected_globs matched "${g}"` };
    }
  }
  if (policy.mutable_globs.length === 0) return { allowed: true };
  for (const g of policy.mutable_globs) {
    if (matchSimpleGlob(relPath, g)) return { allowed: true };
  }
  return { allowed: false, reason: "not in policy.mutable_globs" };
}

/**
 * Tiny glob matcher with bash-globstar semantics.
 *  - `**` (with optional trailing `/`) matches zero or more path segments —
 *    so `src/** /*.ts` (no space) matches both `src/foo.ts` and `src/a/b/foo.ts`.
 *  - `*` matches one segment (no slashes).
 *  - All other chars are literal. No brackets, no negation.
 */
export function matchSimpleGlob(path: string, pattern: string): boolean {
  const escaped = pattern.replace(/[.+^$(){}|[\]\\]/g, "\\$&");
  const final = escaped
    .replace(/\*\*\//g, "__DSDIR__")
    .replace(/\*\*/g, "__DS__")
    .replace(/\*/g, "[^/]*")
    .replace(/__DSDIR__/g, "(?:.*/)?")
    .replace(/__DS__/g, ".*");
  return new RegExp("^" + final + "$").test(path);
}
