/**
 * Public key for verifying Pro license JWTs (RS256).
 *
 * AUTO-GENERATED by scripts/license/generate-keypair.ts — do not edit by hand.
 * Rotating it requires re-issuing every license; read the generator script
 * header before considering it.
 */

export const LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA14Ks/7LAxliSbnbJPu1i
+4CtrJ3+C4cUYK/BpoHy0LzxKYBT2qR3WmNk8XwfP+YlnnrJVBsCJZnNIeJhrG9G
cPxs25e91UeBro6Gol12xSfLY2DO0fxxs63DP2j+iiBxGiOfH9Se6kl1TwjaNmnP
CVoJ/xsuM/uUk1dH3v3mPtUyogr96SGG4w+GLyRt35PeHqTe93+wmo88QWBgGBLw
FPNIvWM+FDEthPUiDdbsW4lCr5MCDKz1js34waBBWk9IP331fre1i3lgmyIu5J20
gSzu3Jz7rvP0NkDS2Xdy1Jjkege7WnG8X23xHwVsHnmsRa0mLSmk4h/GLf/wpHfJ
FwIDAQAB
-----END PUBLIC KEY-----
`;
